remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: true

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Android Project Proposal"
description: "Trust me, it'll be cool!"
author:
  name: "Java+Android Student"

# Do not change the following line.
  copyright: true
